import { motion } from "motion/react";
import { ArrowRight, Clock3, MapPin, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import { Badge } from "@/components/ui/badge";
import type { Lot } from "@/types/auction";

interface MarketLotCardProps { lot: Lot }
const money = (value: number) => `Rp ${(value / 1_000_000).toLocaleString("id-ID", { maximumFractionDigits: 0 })} jt`;
function countdown(end: string, status: Lot["status"]): string { if (status === "ENDED") return "Selesai"; const distance = new Date(end).getTime() - Date.now(); if (distance <= 0) return "Ditutup"; const hours = Math.floor(distance / 3_600_000); const minutes = Math.floor((distance % 3_600_000) / 60_000); return `${String(hours).padStart(2, "0")}j ${String(minutes).padStart(2, "0")}m`; }

export function MarketLotCard({ lot }: MarketLotCardProps) {
  return <motion.article data-testid={`lot-card-${lot.id}`} whileHover={{ y: -4 }} transition={{ duration: 0.2 }} className="group overflow-hidden rounded-xl border border-slate-200 bg-white shadow-[0_2px_8px_rgba(0,0,0,0.05)] transition-shadow hover:shadow-[0_8px_22px_rgba(0,0,0,0.1)]">
    <Link data-testid={`lot-card-link-${lot.id}`} to={`/lots/${lot.id}`} className="block">
      <div className="relative aspect-[16/10] overflow-hidden bg-slate-100"><img data-testid={`lot-image-${lot.id}`} src={lot.image_url} alt={lot.title} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/45 to-transparent" /><Badge data-testid={`lot-status-${lot.id}`} variant="outline" className={`absolute left-3 top-3 border-0 text-[10px] shadow-sm ${lot.status === "LIVE" ? "bg-[#E8F9EA] text-[#03AC0E]" : lot.status === "UPCOMING" ? "bg-white text-slate-700" : "bg-slate-800 text-white"}`}>{lot.status === "LIVE" ? "● Live sekarang" : lot.status === "UPCOMING" ? "Segera dibuka" : "Lelang selesai"}</Badge><span data-testid={`lot-number-${lot.id}`} className="absolute bottom-3 left-3 font-mono text-[10px] font-semibold tracking-wider text-white">{lot.lot_number}</span></div>
      <div className="p-4"><p data-testid={`lot-category-${lot.id}`} className="text-[11px] font-medium text-[#03AC0E]">{lot.category}</p><h3 data-testid={`lot-title-${lot.id}`} className="mt-1 min-h-[44px] font-heading text-[17px] font-bold leading-snug text-slate-800">{lot.title}</h3><div className="mt-4 flex items-end justify-between gap-3"><div><p data-testid={`lot-current-label-${lot.id}`} className="text-[10px] text-slate-400">{lot.status === "ENDED" ? "Harga akhir" : "Bid tertinggi"}</p><p data-testid={`lot-current-bid-${lot.id}`} className="mt-0.5 font-mono text-lg font-bold text-[#03AC0E]">{money(lot.current_bid)}</p></div><div data-testid={`lot-countdown-${lot.id}`} className="text-right"><p className="flex items-center justify-end gap-1 text-[10px] text-slate-400"><Clock3 size={11} /> {lot.status === "LIVE" ? "Berakhir" : "Jadwal"}</p><p className="mt-0.5 text-xs font-semibold text-slate-700">{countdown(lot.auction_end, lot.status)}</p></div></div><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3 text-[11px] text-slate-500"><span data-testid={`lot-location-${lot.id}`} className="flex items-center gap-1"><MapPin size={12} className="text-[#03AC0E]" /> {lot.location}</span><span data-testid={`lot-verified-${lot.id}`} className="flex items-center gap-1 text-[#03AC0E]"><ShieldCheck size={12} /> Verified</span></div><span data-testid={`lot-open-link-${lot.id}`} className="mt-3 flex items-center justify-center gap-1.5 text-xs font-semibold text-[#03AC0E] opacity-0 transition group-hover:opacity-100">Lihat detail lot <ArrowRight size={13} /></span></div>
    </Link>
  </motion.article>;
}