import { useQuery } from "@tanstack/react-query";
import { CalendarClock, Clock3, Layers3 } from "lucide-react";
import { Link } from "react-router-dom";
import { AuctionHeader } from "@/components/auction/MarketHeader";
import { Badge } from "@/components/ui/badge";
import { apiGet } from "@/lib/api";
import type { AuctionSession, Bidder } from "@/types/auction";

interface Props { bidder: Bidder; onBidderChange: (bidder: Bidder) => void }

export default function AuctionSessionsPage({ bidder, onBidderChange }: Props) {
  const query = useQuery({ queryKey: ["auction-sessions"], queryFn: () => apiGet<AuctionSession[]>("/sessions"), retry: false }); const sessions = query.data ?? [];
  return <div data-testid="sessions-page" className="min-h-screen bg-[#f4f4f2]"><AuctionHeader bidder={bidder} onBidderChange={onBidderChange} /><main className="mx-auto max-w-[1100px] px-4 py-8 sm:px-6"><header className="rounded-xl bg-[#202124] p-7 text-white"><p data-testid="sessions-eyebrow" className="text-xs font-bold uppercase tracking-wider text-[#F5B800]">Jadwal MIT Auction</p><h1 data-testid="sessions-heading" className="mt-2 font-heading text-3xl font-bold">Selasa & Jumat, 10.00–15.00 WIB</h1><p data-testid="sessions-description" className="mt-3 max-w-xl text-sm text-slate-300">Setiap sesi dipublikasikan H-3 setelah lotting dan verifikasi data unit selesai.</p></header><section data-testid="sessions-list" className="mt-5 grid gap-4 md:grid-cols-2">{sessions.map((session) => <article data-testid={`session-card-${session.id}`} key={session.id} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#FFF4C2] text-[#8A5B00]"><CalendarClock size={20} /></span><Badge data-testid={`session-status-${session.id}`} className={session.status === "LIVE" ? "bg-[#F5B800] text-[#202124]" : session.status === "CLOSED" ? "bg-slate-200 text-slate-600" : "bg-[#FFF4C2] text-[#8A5B00]"}>{session.status}</Badge></div><p data-testid={`session-code-${session.id}`} className="mt-5 font-mono text-[10px] text-slate-400">{session.code}</p><h2 data-testid={`session-title-${session.id}`} className="mt-1 font-heading text-lg font-bold">{session.title}</h2><p data-testid={`session-time-${session.id}`} className="mt-3 flex items-center gap-2 text-sm text-slate-600"><Clock3 size={15} className="text-[#B77900]" /> {new Date(session.start_at).toLocaleString("id-ID", { dateStyle: "full", timeStyle: "short", timeZone: "Asia/Jakarta" })}</p><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-4"><span data-testid={`session-lot-count-${session.id}`} className="flex items-center gap-1.5 text-xs text-slate-500"><Layers3 size={14} /> {session.lot_ids.length} lot</span><Link data-testid={`session-catalog-link-${session.id}`} to="/#catalog" className="text-xs font-bold text-[#8A5B00]">Lihat unit</Link></div></article>)}{!query.isLoading && sessions.length === 0 && <div data-testid="sessions-empty" className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">Belum ada sesi yang dipublikasikan.</div>}</section></main></div>;
}