import { useQuery } from "@tanstack/react-query";
import { ArrowRight, BadgeCheck, CarFront, Clock3, History, Trophy } from "lucide-react";
import { Link } from "react-router-dom";
import { AuctionHeader } from "@/components/auction/AuctionHeader";
import { Badge } from "@/components/ui/badge";
import { apiGet } from "@/lib/api";
import type { Bid, Bidder } from "@/types/auction";

interface DashboardProps { bidder: Bidder; onBidderChange: (bidder: Bidder) => void }
const money = (value: number) => `Rp ${(value / 1_000_000).toLocaleString("id-ID", { maximumFractionDigits: 0 })} jt`;

export default function Dashboard({ bidder, onBidderChange }: DashboardProps) {
  const bidsQuery = useQuery({ queryKey: ["my-bids", bidder.name], queryFn: () => apiGet<Bid[]>(`/bids/mine?bidder_name=${encodeURIComponent(bidder.name)}`), retry: false });
  const bids = bidsQuery.data ?? [];
  const totalValue = bids.reduce((sum, bid) => sum + bid.amount, 0);
  return <div data-testid="dashboard-page" className="min-h-screen bg-[#060A17] text-[#FAF9F6]"><AuctionHeader bidder={bidder} onBidderChange={onBidderChange} /><main className="mx-auto max-w-[1400px] px-5 py-12 sm:px-8 lg:px-12 lg:py-16"><div data-testid="dashboard-heading-block" className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p data-testid="dashboard-eyebrow" className="font-mono text-[10px] uppercase tracking-[0.22em] text-[#FF5E1F]">Bidder console / {bidder.type}</p><h1 data-testid="dashboard-heading" className="mt-3 font-heading text-4xl font-bold tracking-[-0.05em]">Halo, {bidder.name.split(" ")[0]}.</h1><p data-testid="dashboard-description" className="mt-3 max-w-lg text-sm leading-relaxed text-slate-400">Pantau semua penawaran simulasi dan peluang kemenanganmu dari satu ruang.</p></div><Link data-testid="dashboard-browse-link" to="/#catalog" className="inline-flex items-center gap-2 text-sm font-semibold text-[#FF8e68] transition hover:text-white">Cari lot baru <ArrowRight size={16} /></Link></div>
      <div data-testid="dashboard-summary-grid" className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[{ label: "Total bid", value: String(bids.length), icon: History, accent: "text-[#FF5E1F]" }, { label: "Lot dimenangkan", value: "0", icon: Trophy, accent: "text-[#F59E0B]" }, { label: "Bid aktif", value: String(bids.length > 0 ? Math.min(bids.length, 2) : 0), icon: Clock3, accent: "text-emerald-400" }, { label: "Total nilai bid", value: money(totalValue), icon: CarFront, accent: "text-sky-400" }].map(({ label, value, icon: Icon, accent }, index) => <div data-testid={`dashboard-summary-card-${index}`} key={label} className="rounded-xl border border-white/10 bg-[#111A33]/60 p-5"><Icon data-testid={`dashboard-summary-icon-${index}`} size={18} className={accent} /><p data-testid={`dashboard-summary-label-${index}`} className="mt-5 text-xs text-slate-500">{label}</p><p data-testid={`dashboard-summary-value-${index}`} className="mt-1 font-heading text-2xl font-bold">{value}</p></div>)}</div>
      <section data-testid="dashboard-bids-section" className="mt-10 overflow-hidden rounded-2xl border border-white/10 bg-[#111A33]/50"><div className="flex flex-col justify-between gap-3 border-b border-white/10 p-5 sm:flex-row sm:items-center sm:p-6"><div><p data-testid="dashboard-bids-eyebrow" className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#FF5E1F]">Activity log</p><h2 data-testid="dashboard-bids-heading" className="mt-2 font-heading text-2xl font-bold">Riwayat penawaran</h2></div><Badge data-testid="dashboard-bidder-badge" variant="outline" className="w-fit border-emerald-500/30 bg-emerald-500/10 text-emerald-300"><BadgeCheck size={13} className="mr-1" /> Persona terverifikasi</Badge></div>{bidsQuery.isError && <p data-testid="dashboard-bids-error" className="p-6 text-sm text-red-300">Riwayat bid belum dapat dimuat.</p>}{!bidsQuery.isError && bids.length === 0 && <div data-testid="dashboard-empty-state" className="p-10 text-center"><History data-testid="dashboard-empty-icon" size={28} className="mx-auto text-slate-600" /><p data-testid="dashboard-empty-title" className="mt-4 font-heading font-semibold text-slate-300">Belum ada penawaran.</p><p data-testid="dashboard-empty-description" className="mt-2 text-sm text-slate-500">Masuk ke katalog dan jadilah bid pertama pada lot favoritmu.</p><Link data-testid="dashboard-empty-action" to="/#catalog" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-[#FF8e68]">Jelajahi katalog <ArrowRight size={15} /></Link></div>}{bids.length > 0 && <div data-testid="dashboard-bid-history-list" className="divide-y divide-white/10">{bids.map((bid) => <div data-testid={`dashboard-bid-row-${bid.id}`} key={bid.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div><p data-testid={`dashboard-bid-lot-${bid.id}`} className="font-mono text-[10px] uppercase tracking-[0.14em] text-slate-500">Lot {bid.lot_id}</p><p data-testid={`dashboard-bid-time-${bid.id}`} className="mt-1 text-xs text-slate-400">{new Date(bid.created_at).toLocaleString("id-ID", { dateStyle: "medium", timeStyle: "short" })}</p></div><div className="flex items-center gap-5"><div className="text-right"><p data-testid={`dashboard-bid-amount-${bid.id}`} className="font-mono font-semibold text-[#F59E0B]">{money(bid.amount)}</p><p data-testid={`dashboard-bid-status-${bid.id}`} className="mt-1 text-[10px] uppercase tracking-[0.12em] text-emerald-400">{bid.status === "VALID" ? "Bid valid" : "Outbid"}</p></div><Link data-testid={`dashboard-bid-open-${bid.id}`} to={`/lots/${bid.lot_id}`} className="flex h-8 w-8 items-center justify-center rounded-full border border-white/10 text-slate-400 transition hover:border-[#FF5E1F] hover:text-[#FF5E1F]"><ArrowRight size={15} /></Link></div></div>)}</div>}</section>
    </main></div>;
}