import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Banknote, Check, FileText, WalletCards } from "lucide-react";
import { AuctionHeader } from "@/components/auction/MarketHeader";
import { AdminRoleBar } from "@/components/admin/AdminRoleBar";
import { Button } from "@/components/ui/button";
import { apiGet, apiPatch } from "@/lib/api";
import type { AdminUser, Bidder, BuyerProfile, DepositReviewItem, Invoice } from "@/types/auction";

interface Props { bidder: Bidder; onBidderChange: (bidder: Bidder) => void; adminUser: AdminUser }

export default function FinanceDashboard({ bidder, onBidderChange, adminUser }: Props) {
  const client = useQueryClient(); const memberships = useQuery({ queryKey: ["finance-memberships"], queryFn: () => apiGet<DepositReviewItem[]>("/admin/member-payments"), retry: false }); const deposits = useQuery({ queryKey: ["finance-deposits"], queryFn: () => apiGet<DepositReviewItem[]>("/admin/deposits"), retry: false }); const invoices = useQuery({ queryKey: ["finance-invoices"], queryFn: () => apiGet<Invoice[]>("/admin/invoices"), retry: false });
  const confirmMember = useMutation({ mutationFn: (id: string) => apiPatch<BuyerProfile>(`/admin/member-payments/${id}`, { status: "CONFIRMED", reason: "Biaya member terverifikasi" }), onSuccess: async () => client.invalidateQueries({ queryKey: ["finance-memberships"] }) });
  const confirmDeposit = useMutation({ mutationFn: (id: string) => apiPatch<BuyerProfile>(`/admin/deposits/${id}`, { status: "CONFIRMED", reason: "Deposit terverifikasi" }), onSuccess: async () => client.invalidateQueries({ queryKey: ["finance-deposits"] }) });
  const confirmInvoice = useMutation({ mutationFn: (id: string) => apiPatch<Invoice>(`/admin/invoices/${id}`, { status: "CONFIRMED", reason: "Pelunasan terverifikasi" }), onSuccess: async () => client.invalidateQueries({ queryKey: ["finance-invoices"] }) });
  return <div data-testid="finance-dashboard-page" className="min-h-screen bg-[#f4f4f2]"><AuctionHeader bidder={bidder} onBidderChange={onBidderChange} /><main className="mx-auto max-w-[1100px] px-4 py-7 sm:px-6"><AdminRoleBar role={adminUser.role} onRoleChange={() => undefined} /><header className="rounded-xl bg-[#202124] p-7 text-white"><p className="text-xs font-bold uppercase tracking-wide text-[#F5B800]">Finance MPI</p><h1 data-testid="finance-heading" className="mt-2 font-heading text-3xl font-bold">Pembayaran & rekonsiliasi</h1><p className="mt-2 text-sm text-slate-300">Pemisahan tugas: Finance memverifikasi uang masuk, Admin MPI memvalidasi pemenang.</p></header><div className="mt-5 grid gap-5 lg:grid-cols-3"><Queue title="Biaya member" icon={FileText} items={memberships.data ?? []} empty="Tidak ada biaya member pending" onConfirm={(id) => confirmMember.mutate(id)} testId="finance-membership-queue" /><Queue title="Deposit bidding" icon={WalletCards} items={deposits.data ?? []} empty="Tidak ada deposit pending" onConfirm={(id) => confirmDeposit.mutate(id)} testId="finance-deposit-queue" /><section data-testid="finance-invoice-queue" className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-2 border-b border-slate-100 p-5"><Banknote size={18} className="text-[#9A6700]" /><h2 className="font-heading text-lg font-bold">Pelunasan pemenang</h2></div><div className="divide-y divide-slate-100">{(invoices.data ?? []).map((invoice) => <div data-testid={`finance-invoice-${invoice.id}`} key={invoice.id} className="p-4"><p className="text-sm font-semibold">{invoice.bidder_name}</p><p className="mt-1 text-xs text-slate-500">{invoice.invoice_number} · {invoice.status}</p><p className="mt-2 font-mono text-sm font-bold">Rp {invoice.total_due.toLocaleString("id-ID")}</p>{invoice.status === "PAYMENT_REVIEW" && <Button data-testid={`confirm-invoice-${invoice.id}`} size="sm" onClick={() => confirmInvoice.mutate(invoice.id)} className="mt-3 bg-[#F5B800] text-[#202124]"><Check size={14} /> Konfirmasi lunas</Button>}</div>)}</div></section></div></main></div>;
}

function Queue({ title, icon: Icon, items, empty, onConfirm, testId }: { title: string; icon: typeof FileText; items: DepositReviewItem[]; empty: string; onConfirm: (id: string) => void; testId: string }) { return <section data-testid={testId} className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-2 border-b border-slate-100 p-5"><Icon size={18} className="text-[#9A6700]" /><h2 className="font-heading text-lg font-bold">{title}</h2></div><div className="divide-y divide-slate-100">{items.map((item) => <div data-testid={`${testId}-${item.buyer_id}`} key={item.buyer_id} className="p-4"><p className="text-sm font-semibold">{item.bidder_name}</p><p className="mt-1 text-xs text-slate-500">Rp {item.amount.toLocaleString("id-ID")}</p><Button data-testid={`confirm-${testId}-${item.buyer_id}`} size="sm" onClick={() => onConfirm(item.buyer_id)} className="mt-3 bg-[#F5B800] text-[#202124]"><Check size={14} /> Konfirmasi</Button></div>)}{items.length === 0 && <p className="p-6 text-center text-xs text-slate-500">{empty}</p>}</div></section>; }