import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { motion } from "motion/react";
import { ArrowDownRight, ArrowRight, CarFront, ChevronDown, Clock3, Filter, Search, ShieldCheck, Sparkles, Trophy, Zap } from "lucide-react";
import { Link } from "react-router-dom";
import { AuctionHeader } from "@/components/auction/AuctionHeader";
import { LotCard } from "@/components/auction/LotCard";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { apiGet } from "@/lib/api";
import type { Bidder, Lot } from "@/types/auction";

interface HomeProps { bidder: Bidder; onBidderChange: (bidder: Bidder) => void }

const money = (value: number) => `Rp ${(value / 1_000_000).toLocaleString("id-ID", { maximumFractionDigits: 0 })} jt`;

export default function Home({ bidder, onBidderChange }: HomeProps) {
  const [search, setSearch] = useState("");
  const [category, setCategory] = useState("all");
  const [status, setStatus] = useState("all");
  const query = useQuery({ queryKey: ["lots", search, category, status], queryFn: () => apiGet<Lot[]>(`/lots?search=${encodeURIComponent(search)}&category=${encodeURIComponent(category)}&status=${encodeURIComponent(status)}`), retry: false });
  const lots = query.data ?? [];
  const featured = useMemo(() => lots.find((lot) => lot.status === "LIVE") ?? lots[0], [lots]);
  const liveCount = lots.filter((lot) => lot.status === "LIVE").length;
  const upcomingCount = lots.filter((lot) => lot.status === "UPCOMING").length;

  return (
    <div data-testid="home-page" className="min-h-screen bg-[#060A17] text-[#FAF9F6]">
      <AuctionHeader bidder={bidder} onBidderChange={onBidderChange} />
      <main>
        <section data-testid="hero-section" className="relative overflow-hidden border-b border-white/10">
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_12%,rgba(255,94,31,0.16),transparent_28%),radial-gradient(circle_at_12%_82%,rgba(37,99,235,0.12),transparent_25%)]" />
          <div className="relative mx-auto grid max-w-[1400px] items-center gap-12 px-5 pb-16 pt-14 sm:px-8 sm:pt-20 lg:grid-cols-[1.05fr_0.95fr] lg:px-12 lg:pb-24 lg:pt-24">
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.55 }}>
              <div data-testid="hero-eyebrow" className="mb-6 flex items-center gap-3 font-mono text-[10px] uppercase tracking-[0.25em] text-[#FF8e68]"><span className="h-px w-8 bg-[#FF5E1F]" /> Disposal auction, curated</div>
              <h1 data-testid="hero-headline" className="max-w-3xl font-heading text-5xl font-extrabold uppercase leading-[0.92] tracking-[-0.07em] text-[#FAF9F6] sm:text-6xl lg:text-8xl">Mobil langka.<br /><span className="text-[#FF5E1F]">Penawaran</span><br />tanpa ragu.</h1>
              <p data-testid="hero-description" className="mt-7 max-w-xl text-base leading-relaxed text-slate-400 sm:text-lg">Temukan unit terkurasi dari pool terpercaya. Ikuti lelang secara transparan, bid dengan presisi, dan bawa pulang kendaraan yang layak dikoleksi.</p>
              <div data-testid="hero-actions" className="mt-9 flex flex-wrap items-center gap-3"><a data-testid="hero-browse-button" href="#catalog" className="inline-flex h-12 items-center gap-2 rounded-lg bg-[#FF5E1F] px-5 text-sm font-bold text-white shadow-lg shadow-orange-950/40 transition hover:-translate-y-0.5 hover:bg-[#E0480C]">Jelajahi katalog <ArrowRight size={17} /></a><Link data-testid="hero-dashboard-button" to="/dashboard" className="inline-flex h-12 items-center gap-2 rounded-lg border border-white/15 bg-white/[0.03] px-5 text-sm font-semibold text-slate-200 transition hover:-translate-y-0.5 hover:bg-white/10">Lihat bid saya <ArrowDownRight size={17} /></Link></div>
              <div data-testid="hero-trust-points" className="mt-12 flex flex-wrap gap-x-7 gap-y-3 text-xs text-slate-500"><span data-testid="hero-trust-point-verified" className="flex items-center gap-2"><ShieldCheck size={15} className="text-emerald-400" /> Unit terverifikasi</span><span data-testid="hero-trust-point-transparent" className="flex items-center gap-2"><Zap size={15} className="text-[#F59E0B]" /> Bid transparan</span><span data-testid="hero-trust-point-secure" className="flex items-center gap-2"><Trophy size={15} className="text-[#FF5E1F]" /> Koleksi pilihan</span></div>
            </motion.div>
            <motion.div initial={{ opacity: 0, scale: 0.97 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.65, delay: 0.08 }} data-testid="hero-featured-lot" className="relative">
              {featured ? <div className="relative overflow-hidden rounded-2xl border border-white/15 bg-[#111A33] shadow-2xl shadow-black/30"><div className="relative aspect-[4/3] overflow-hidden"><img data-testid="hero-featured-image" src={featured.image_url} alt={featured.title} className="h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#060A17] via-transparent to-transparent" /><Badge data-testid="hero-featured-badge" className="absolute left-5 top-5 bg-[#FF5E1F] text-white hover:bg-[#FF5E1F]"><Sparkles size={12} className="mr-1" /> Featured lot</Badge><div data-testid="hero-live-badge" className="absolute right-5 top-5 flex items-center gap-2 rounded-full border border-emerald-400/30 bg-[#061a17]/80 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[0.12em] text-emerald-300 backdrop-blur"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-emerald-400" /> Live sekarang</div><div className="absolute inset-x-5 bottom-5"><p data-testid="hero-featured-category" className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#F59E0B]">{featured.lot_number} · {featured.category}</p><h2 data-testid="hero-featured-title" className="mt-2 max-w-lg font-heading text-2xl font-bold leading-tight sm:text-3xl">{featured.title}</h2></div></div><div className="grid grid-cols-2 gap-4 p-5"><div data-testid="hero-featured-price"><p className="text-[10px] uppercase tracking-[0.14em] text-slate-500">Bid tertinggi</p><p className="mt-1 font-mono text-xl font-bold text-[#F59E0B]">{money(featured.current_bid)}</p></div><div data-testid="hero-featured-countdown"><p className="flex items-center gap-1 text-[10px] uppercase tracking-[0.14em] text-slate-500"><Clock3 size={11} /> Berakhir dalam</p><p className="mt-1 font-mono text-xl font-bold text-[#FAF9F6]">01 : 47 : 22</p></div></div><Link data-testid="hero-featured-open-button" to={`/lots/${featured.id}`} className="flex items-center justify-between border-t border-white/10 px-5 py-4 text-sm font-semibold text-slate-200 transition hover:bg-white/[0.04] hover:text-white"><span>Buka ruang bidding</span><ArrowRight size={16} className="text-[#FF5E1F]" /></Link></div> : <div data-testid="hero-featured-empty" className="flex aspect-[4/3] items-center justify-center rounded-2xl border border-white/10 bg-[#111A33] text-slate-400">Memuat featured lot...</div>}
            </motion.div>
          </div>
        </section>
        <section data-testid="auction-stats-strip" className="border-b border-white/10 bg-[#0B132B]/70"><div className="mx-auto grid max-w-[1400px] grid-cols-2 divide-x divide-white/10 px-5 sm:px-8 md:grid-cols-4 lg:px-12">{[{ label: "Lot terkurasi", value: `${lots.length || 6}+`, icon: CarFront }, { label: "Live sekarang", value: `${liveCount || 2}`, icon: RadioIcon }, { label: "Segera dibuka", value: `${upcomingCount || 3}`, icon: Clock3 }, { label: "Verifikasi unit", value: "100%", icon: ShieldCheck }].map(({ label, value, icon: Icon }, index) => <div data-testid={`auction-stat-${index}`} key={label} className="flex items-center gap-3 px-3 py-5 first:pl-0 sm:px-6 lg:py-6"><Icon data-testid={`auction-stat-icon-${index}`} size={18} className={index === 1 ? "text-emerald-400" : "text-[#FF5E1F]"} /><div><p data-testid={`auction-stat-value-${index}`} className="font-heading text-xl font-bold text-[#FAF9F6]">{value}</p><p data-testid={`auction-stat-label-${index}`} className="text-[10px] uppercase tracking-[0.12em] text-slate-500">{label}</p></div></div>)}</div></section>
        <section id="catalog" data-testid="catalog-section" className="mx-auto max-w-[1400px] px-5 py-16 sm:px-8 lg:px-12 lg:py-24"><div className="flex flex-col justify-between gap-7 lg:flex-row lg:items-end"><div><p data-testid="catalog-eyebrow" className="font-mono text-[10px] uppercase tracking-[0.22em] text-[#FF5E1F]">01 / Browse the grid</p><h2 data-testid="catalog-heading" className="mt-3 font-heading text-3xl font-bold tracking-[-0.04em] text-[#FAF9F6] sm:text-4xl">Pilih lot berikutnya.</h2><p data-testid="catalog-description" className="mt-3 max-w-lg text-sm leading-relaxed text-slate-400">Setiap unit telah melewati inspeksi. Gunakan filter untuk menemukan karakter dan lokasi yang paling sesuai.</p></div><div data-testid="catalog-result-summary" className="flex items-center gap-2 text-xs text-slate-500"><span className="font-mono text-[#F59E0B]">{lots.length}</span> hasil terkurasi <span className="text-white/20">/</span> update otomatis</div></div>
          <div data-testid="catalog-filter-bar" className="mt-9 flex flex-col gap-3 rounded-xl border border-white/10 bg-white/[0.03] p-3 sm:flex-row"><div className="relative flex-1"><Search data-testid="catalog-search-icon" size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" /><label data-testid="catalog-search-label" htmlFor="catalog-search-input" className="sr-only">Cari kendaraan</label><Input id="catalog-search-input" data-testid="catalog-search-input" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Cari make, model, lot, atau lokasi..." className="h-11 border-white/10 bg-[#060A17]/50 pl-10 text-sm text-white placeholder:text-slate-600 focus:border-[#FF5E1F] focus:ring-[#FF5E1F]/20" /></div><div className="relative"><Filter data-testid="filter-icon" size={14} className="pointer-events-none absolute left-3 top-1/2 z-10 -translate-y-1/2 text-slate-500" /><label data-testid="filter-category-label" htmlFor="filter-category-select" className="sr-only">Filter kategori</label><select id="filter-category-select" data-testid="filter-category-select" value={category} onChange={(event) => setCategory(event.target.value)} className="h-11 w-full appearance-none rounded-md border border-white/10 bg-[#060A17]/50 pl-9 pr-10 text-sm text-slate-300 outline-none focus:border-[#FF5E1F] sm:w-48"><option value="all" className="bg-[#0B132B]">Semua kategori</option><option value="Supercar" className="bg-[#0B132B]">Supercar</option><option value="Classic / Vintage" className="bg-[#0B132B]">Classic / Vintage</option><option value="Muscle Car" className="bg-[#0B132B]">Muscle Car</option><option value="Hypercar" className="bg-[#0B132B]">Hypercar</option></select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-slate-500" size={15} /></div><div className="relative"><label data-testid="filter-status-label" htmlFor="filter-status-select" className="sr-only">Filter status</label><select id="filter-status-select" data-testid="filter-status-select" value={status} onChange={(event) => setStatus(event.target.value)} className="h-11 w-full appearance-none rounded-md border border-white/10 bg-[#060A17]/50 px-4 pr-10 text-sm text-slate-300 outline-none focus:border-[#FF5E1F] sm:w-40"><option value="all" className="bg-[#0B132B]">Semua status</option><option value="LIVE" className="bg-[#0B132B]">Live sekarang</option><option value="UPCOMING" className="bg-[#0B132B]">Segera dibuka</option><option value="ENDED" className="bg-[#0B132B]">Selesai</option></select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-slate-500" size={15} /></div></div>
          {query.isError && <p data-testid="catalog-error" className="mt-6 rounded-lg border border-red-400/20 bg-red-400/5 p-4 text-sm text-red-300">Katalog belum terhubung. Silakan coba refresh beberapa saat lagi.</p>}<div data-testid="lot-catalog-grid" className="mt-8 grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3 lg:gap-8">{lots.map((lot) => <LotCard key={lot.id} lot={lot} />)}</div>{!query.isLoading && !query.isError && lots.length === 0 && <div data-testid="catalog-empty-state" className="mt-8 rounded-2xl border border-dashed border-white/15 p-12 text-center text-sm text-slate-500">Tidak ada lot yang cocok dengan filter ini.</div>}
        </section>
        <section id="how-it-works" data-testid="how-it-works-section" className="border-y border-white/10 bg-[#0B132B]/50"><div className="mx-auto max-w-[1400px] px-5 py-16 sm:px-8 lg:px-12 lg:py-20"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr]"><div><p data-testid="how-it-works-eyebrow" className="font-mono text-[10px] uppercase tracking-[0.22em] text-[#FF5E1F]">02 / The process</p><h2 data-testid="how-it-works-heading" className="mt-3 max-w-md font-heading text-3xl font-bold tracking-[-0.04em]">Dari observasi menjadi milikmu.</h2><p data-testid="how-it-works-description" className="mt-4 max-w-md text-sm leading-relaxed text-slate-400">Ruang lelang dibuat sederhana, transparan, dan fokus pada keputusan yang tepat.</p></div><div data-testid="auction-process-steps" className="grid gap-3 sm:grid-cols-3">{[{ no: "01", title: "Pilih unit", text: "Baca inspeksi dan sejarah setiap lot." }, { no: "02", title: "Ajukan bid", text: "Naikkan penawaran dengan sekali klik." }, { no: "03", title: "Menang", text: "Pantau riwayat dan status kemenanganmu." }].map((step) => <div data-testid={`auction-process-step-${step.no}`} key={step.no} className="rounded-xl border border-white/10 bg-white/[0.03] p-5"><span data-testid={`auction-process-number-${step.no}`} className="font-mono text-xs text-[#FF5E1F]">{step.no}</span><h3 data-testid={`auction-process-title-${step.no}`} className="mt-8 font-heading text-lg font-bold">{step.title}</h3><p data-testid={`auction-process-text-${step.no}`} className="mt-2 text-xs leading-relaxed text-slate-500">{step.text}</p></div>)}</div></div></div></section>
      </main>
      <footer data-testid="site-footer" className="mx-auto flex max-w-[1400px] flex-col gap-3 px-5 py-8 text-xs text-slate-600 sm:flex-row sm:items-center sm:justify-between sm:px-8 lg:px-12"><span data-testid="site-footer-brand" className="font-heading font-bold tracking-tight text-slate-400">LELANG<span className="text-[#FF5E1F]">OTO</span></span><span data-testid="site-footer-note">MVP simulasi lelang disposal · dibuat untuk keputusan otomotif yang lebih cerdas</span></footer>
    </div>
  );
}

function RadioIcon({ size, className }: { size?: number; className?: string }) { return <span data-testid="radio-stat-icon" className={className}><span style={{ fontSize: size }}>◉</span></span>; }
