import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Camera, ClipboardCheck } from "lucide-react";
import { AuctionHeader } from "@/components/auction/MarketHeader";
import { AdminRoleBar } from "@/components/admin/AdminRoleBar";
import { Button } from "@/components/ui/button";
import { apiGet, apiPatch, apiUpload } from "@/lib/api";
import type { AdminUser, Bidder, InspectionRecord } from "@/types/auction";

interface Props { bidder: Bidder; onBidderChange: (bidder: Bidder) => void; adminUser: AdminUser }
const components = ["eksterior", "interior", "mesin", "kaki_kaki", "kelistrikan", "kelengkapan", "pembacaan"];

export default function InspectionDashboard({ bidder, onBidderChange, adminUser }: Props) {
  const client = useQueryClient(); const query = useQuery({ queryKey: ["inspection-tasks"], queryFn: () => apiGet<InspectionRecord[]>("/admin/inspections"), retry: false }); const [scores, setScores] = useState<Record<string, number>>(Object.fromEntries(components.map((key) => [key, 80]))); const [notes, setNotes] = useState(""); const [photo, setPhoto] = useState<File | null>(null);
  const submit = useMutation({ mutationFn: (id: string) => apiPatch<InspectionRecord>(`/admin/inspections/${id}`, { component_scores: scores, notes }), onSuccess: async () => client.invalidateQueries({ queryKey: ["inspection-tasks"] }) });
  const upload = useMutation({ mutationFn: async (id: string) => { if (!photo) throw new Error("Pilih foto"); const data = new FormData(); data.append("file", photo); return apiUpload<InspectionRecord>(`/admin/inspections/${id}/photos/front`, data); }, onSuccess: async () => client.invalidateQueries({ queryKey: ["inspection-tasks"] }) });
  return <div data-testid="inspection-dashboard-page" className="min-h-screen bg-[#f4f4f2]"><AuctionHeader bidder={bidder} onBidderChange={onBidderChange} /><main className="mx-auto max-w-[1000px] px-4 py-7 sm:px-6"><AdminRoleBar role={adminUser.role} onRoleChange={() => undefined} /><header className="rounded-xl bg-[#202124] p-7 text-white"><p className="text-xs font-bold uppercase tracking-wide text-[#F5B800]">Inspektor MPI</p><h1 data-testid="inspection-heading" className="mt-2 font-heading text-3xl font-bold">Pengecekan fisik & grading</h1><p className="mt-2 text-sm text-slate-300">Nilai tujuh kelompok komponen dan unggah foto slot terstruktur.</p></header><section data-testid="inspection-task-list" className="mt-5 space-y-4">{(query.data ?? []).map((task) => <article data-testid={`inspection-task-${task.id}`} key={task.id} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="font-mono text-[10px] text-slate-400">Lot {task.lot_id}</p><h2 className="mt-1 font-heading text-lg font-bold">Tugas {task.inspector_name}</h2><p className="mt-1 text-xs text-slate-500">{new Date(task.planned_at).toLocaleString("id-ID")} · {task.status}</p></div>{task.suggested_grade && <span data-testid={`inspection-grade-${task.id}`} className="rounded-full bg-[#FFF4C2] px-3 py-1 text-sm font-bold text-[#8A5B00]">Grade {task.suggested_grade} · {task.total_score}</span>}</div>{task.status !== "COMPLETED" && <><div className="mt-5 grid gap-3 sm:grid-cols-4">{components.map((component) => <label key={component} className="text-xs font-semibold capitalize">{component.replace("_", " ")}<input data-testid={`inspection-score-${component}`} type="number" min="0" max="100" value={scores[component]} onChange={(event) => setScores((current) => ({ ...current, [component]: Number(event.target.value) }))} className="mt-1 h-9 w-full rounded-lg border border-slate-200 bg-slate-50 px-2" /></label>)}</div><textarea data-testid="inspection-notes" value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Catatan kondisi unit" className="mt-4 min-h-20 w-full rounded-lg border border-slate-200 bg-slate-50 p-3 text-sm" /><div className="mt-4 flex flex-col gap-2 sm:flex-row"><label className="flex flex-1 items-center gap-2 rounded-lg border border-dashed border-slate-300 p-2 text-xs"><Camera size={15} /><input data-testid="inspection-front-photo" type="file" accept="image/jpeg,image/png" onChange={(event) => setPhoto(event.target.files?.[0] ?? null)} /></label><Button data-testid={`inspection-upload-${task.id}`} type="button" disabled={!photo} onClick={() => upload.mutate(task.id)} variant="outline">Upload foto depan</Button><Button data-testid={`inspection-submit-${task.id}`} type="button" onClick={() => submit.mutate(task.id)} className="bg-[#F5B800] text-[#202124]"><ClipboardCheck size={15} /> Selesaikan & grading</Button></div></>}</article>)}</section></main></div>;
}