import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, Check, FileCheck2, Gauge, MapPin, ShieldCheck } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { AuctionHeader } from "@/components/auction/AuctionHeader";
import { BidPanel } from "@/components/auction/BidPanel";
import { Badge } from "@/components/ui/badge";
import { apiGet } from "@/lib/api";
import type { Bid, Bidder, Lot } from "@/types/auction";

interface LotDetailProps { bidder: Bidder; onBidderChange: (bidder: Bidder) => void }
const money = (value: number) => `Rp ${value.toLocaleString("id-ID")}`;

export default function LotDetail({ bidder, onBidderChange }: LotDetailProps) {
  const { lotId } = useParams();
  const lotQuery = useQuery({ queryKey: ["lot", lotId], queryFn: () => apiGet<Lot>(`/lots/${lotId}`), enabled: Boolean(lotId), retry: false });
  const bidsQuery = useQuery({ queryKey: ["lot-bids", lotId], queryFn: () => apiGet<Bid[]>(`/lots/${lotId}/bids`), enabled: Boolean(lotId), retry: false });
  const lot = lotQuery.data;
  const bids = bidsQuery.data ?? [];

  return <div data-testid="lot-detail-page" className="min-h-screen bg-[#060A17] text-[#FAF9F6]"><AuctionHeader bidder={bidder} onBidderChange={onBidderChange} /><main className="mx-auto max-w-[1400px] px-5 py-8 sm:px-8 lg:px-12 lg:py-12">
    <Link data-testid="lot-detail-back-link" to="/#catalog" className="mb-8 inline-flex items-center gap-2 text-xs font-semibold text-slate-400 transition hover:text-white"><ArrowLeft size={14} /> Kembali ke katalog</Link>
    {lotQuery.isLoading && <div data-testid="lot-detail-loading" className="rounded-2xl border border-white/10 bg-[#111A33] p-12 text-center text-slate-400">Memuat detail lot...</div>}
    {lotQuery.isError && <div data-testid="lot-detail-error" className="rounded-2xl border border-red-400/20 bg-red-400/5 p-12 text-center"><p data-testid="lot-detail-error-title" className="font-heading text-xl font-bold text-red-200">Lot tidak ditemukan</p><p data-testid="lot-detail-error-description" className="mt-2 text-sm text-red-300/70">Kembali ke katalog untuk melihat unit lain.</p></div>}
    {lot && <>
      <div data-testid="lot-detail-intro" className="mb-9 flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><div className="flex flex-wrap items-center gap-2"><span data-testid="lot-detail-number" className="font-mono text-xs tracking-[0.2em] text-[#FF5E1F]">{lot.lot_number}</span><Badge data-testid="lot-detail-category" variant="outline" className="border-white/15 text-slate-400">{lot.category}</Badge>{lot.seller_verified && <span data-testid="lot-detail-seller-verified" className="flex items-center gap-1 text-xs text-emerald-400"><ShieldCheck size={14} /> Penjual terverifikasi</span>}</div><h1 data-testid="lot-detail-title" className="mt-4 max-w-4xl font-heading text-4xl font-bold leading-tight tracking-[-0.05em] sm:text-5xl">{lot.title}</h1><p data-testid="lot-detail-location" className="mt-4 flex items-center gap-2 text-sm text-slate-400"><MapPin size={15} className="text-[#FF5E1F]" /> {lot.location} <span className="text-white/20">·</span> {lot.document_status}</p></div><div data-testid="lot-detail-current-bid" className="lg:text-right"><p className="text-xs uppercase tracking-[0.14em] text-slate-500">Bid tertinggi saat ini</p><p className="mt-1 font-mono text-3xl font-bold text-[#F59E0B]">{money(lot.current_bid)}</p></div></div>
      <div className="grid gap-8 lg:grid-cols-[1.3fr_0.7fr]">
        <div className="space-y-8"><div data-testid="lot-detail-gallery" className="overflow-hidden rounded-2xl border border-white/10 bg-[#111A33]"><div className="relative aspect-[16/9]"><img data-testid="lot-detail-main-image" src={lot.image_url} alt={lot.title} className="h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#060A17]/60 to-transparent" /><div data-testid="lot-detail-inspection-badge" className="absolute bottom-5 left-5 rounded-xl border border-white/15 bg-[#060A17]/80 px-4 py-3 backdrop-blur"><p className="text-[10px] uppercase tracking-[0.16em] text-slate-500">Inspection score</p><p className="mt-1 font-mono text-xl font-bold text-emerald-300">{lot.inspection_score}<span className="text-sm text-slate-400"> / 100</span></p></div></div></div>
          <section data-testid="lot-specs-section" className="rounded-2xl border border-white/10 bg-[#111A33]/60 p-5 sm:p-7"><div className="flex items-center justify-between"><div><p data-testid="lot-specs-eyebrow" className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#FF5E1F]">Technical sheet</p><h2 data-testid="lot-specs-heading" className="mt-2 font-heading text-2xl font-bold">Detail kendaraan</h2></div><Gauge data-testid="lot-specs-icon" size={24} className="text-[#FF5E1F]" /></div><div data-testid="lot-specs-grid" className="mt-6 grid grid-cols-2 gap-x-5 gap-y-5 sm:grid-cols-4">{[["Tahun", lot.year], ["Jarak tempuh", lot.mileage], ["Transmisi", lot.transmission], ["Mesin", lot.engine], ["Grade", lot.grade], ["VIN", lot.vin], ["Harga dasar", money(lot.base_price)], ["Kenaikan minimum", money(lot.minimum_increment)]].map(([label, value], index) => <div data-testid={`lot-spec-${index}`} key={String(label)} className="border-t border-white/10 pt-3"><p data-testid={`lot-spec-label-${index}`} className="text-[10px] uppercase tracking-[0.14em] text-slate-500">{label}</p><p data-testid={`lot-spec-value-${index}`} className="mt-1 text-sm font-semibold leading-relaxed text-slate-200">{value}</p></div>)}</div></section>
          <section data-testid="lot-description-section" className="grid gap-8 border-t border-white/10 pt-8 md:grid-cols-[1fr_0.8fr]"><div><p data-testid="lot-description-eyebrow" className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#FF5E1F]">Inspection notes</p><h2 data-testid="lot-description-heading" className="mt-2 font-heading text-2xl font-bold">Dibuat untuk dikendarai.</h2><p data-testid="lot-description-text" className="mt-4 text-sm leading-relaxed text-slate-400">{lot.description}</p></div><div data-testid="lot-feature-list"><p data-testid="lot-feature-list-title" className="mb-3 text-xs font-semibold text-slate-300">Highlights unit</p>{lot.features.map((feature, index) => <p data-testid={`lot-feature-${index}`} key={feature} className="flex items-center gap-2 border-b border-white/10 py-2.5 text-xs text-slate-400"><Check size={14} className="text-emerald-400" /> {feature}</p>)}</div></section>
        </div>
        <div className="lg:sticky lg:top-28 lg:h-fit"><BidPanel lot={lot} bids={bids} bidder={bidder} /></div>
      </div>
      <section data-testid="lot-detail-bottom-bar" className="mt-10 flex flex-col gap-4 rounded-xl border border-white/10 bg-[#0B132B]/70 p-4 sm:flex-row sm:items-center sm:justify-between sm:p-5"><div className="flex items-center gap-3"><FileCheck2 data-testid="lot-document-icon" size={20} className="text-emerald-400" /><div><p data-testid="lot-document-title" className="text-sm font-semibold">Dokumen unit tersedia</p><p data-testid="lot-document-description" className="mt-1 text-xs text-slate-500">BPKB, STNK, dan laporan inspeksi dapat ditinjau setelah memenangkan lot.</p></div></div><span data-testid="lot-document-status" className="text-xs font-semibold text-emerald-300">{lot.document_status}</span></section>
    </>}
  </main></div>;
}