import { useState } from "react";
import type { FormEvent } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { LockKeyhole, Pickaxe, UserRound } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { apiPost } from "@/lib/api";
import type { AdminSessionResponse } from "@/types/auction";

export default function MITAdminLogin() {
  const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const navigate = useNavigate(); const client = useQueryClient();
  const mutation = useMutation({ mutationFn: () => apiPost<AdminSessionResponse>("/admin/auth/login", { username, password }), onSuccess: (session) => { client.setQueryData(["admin-session"], session.user); navigate("/admin", { replace: true }); } });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); mutation.mutate(); };
  return <div data-testid="admin-login-page" className="flex min-h-screen items-center justify-center bg-[#f4f4f2] px-4"><main className="w-full max-w-md"><Link data-testid="admin-login-brand" to="/" className="mb-6 flex items-center justify-center gap-2 font-heading text-xl font-bold text-[#202124]"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#F5B800] text-[#202124]"><Pickaxe size={20} /></span> MIT <span className="-ml-1 text-[#B77900]">Auction</span></Link><form data-testid="admin-login-form" onSubmit={submit} className="rounded-2xl border border-slate-200 bg-white p-7 shadow-[0_12px_40px_rgba(0,0,0,0.08)]"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-[#FFF4C2] text-[#8A5B00]"><LockKeyhole size={22} /></div><h1 data-testid="admin-login-heading" className="mt-5 font-heading text-2xl font-bold">Login pengelola MIT</h1><p data-testid="admin-login-description" className="mt-2 text-sm text-slate-500">Masuk sebagai Super Admin atau Reviewer unit disposal.</p><label data-testid="admin-username-label" htmlFor="admin-username" className="mt-6 block text-xs font-semibold text-slate-600">Username</label><div className="relative mt-1.5"><UserRound size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input id="admin-username" data-testid="admin-username-input" required value={username} onChange={(event) => setUsername(event.target.value)} className="h-11 w-full rounded-lg border border-slate-200 bg-slate-50 pl-9 pr-3 text-sm outline-none focus:border-[#F5B800] focus:bg-white focus:ring-2 focus:ring-[#F5B800]/20" /></div><label data-testid="admin-password-label" htmlFor="admin-password" className="mt-4 block text-xs font-semibold text-slate-600">Password</label><input id="admin-password" data-testid="admin-password-input" required type="password" value={password} onChange={(event) => setPassword(event.target.value)} className="mt-1.5 h-11 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 text-sm outline-none focus:border-[#F5B800] focus:bg-white focus:ring-2 focus:ring-[#F5B800]/20" /><Button data-testid="admin-login-submit" type="submit" disabled={mutation.isPending} className="mt-6 w-full bg-[#F5B800] font-bold text-[#202124] hover:bg-[#D89E00]">{mutation.isPending ? "Memeriksa akun..." : "Masuk ke Admin Console"}</Button>{mutation.isError && <p data-testid="admin-login-error" className="mt-3 rounded-lg bg-red-50 p-3 text-xs text-red-600">Username atau password tidak sesuai.</p>}<Link data-testid="admin-login-home-link" to="/" className="mt-5 block text-center text-xs text-slate-500 hover:text-[#8A5B00]">Kembali ke MIT Auction</Link></form></main></div>;
}